### ISSUE TITLE
Event wizard does not close after /event confirm

### ISSUE THREAD

**Issue by phraustbyte** [DreamExposure/DisCal-Discord-Bot#120]
## *How* do we replicate the issue?
1. `/event create Name`
2. `/event start 2021 December 24 00 00`
3. `/event end 2021 December 24 23 59`
4. `/event confirm`
![image](https://user-images.githubusercontent.com/22650037/143498092-d3971e85-6069-42e1-91ea-600e195c55bf.png)
5. Start a second event command
![image](https://user-images.githubusercontent.com/22650037/143498110-d1d4ebc0-6030-4cd7-bef2-5d9e6f6c8adf.png)

In order to proceed to the next event command, `/event cancel` can be used as a workaround as the event is already saved, however, the wizard is still open

## Expected behavior (i.e. solution)
On `/event confirm`, the wizard should complete without having to enter `/event cancel`

## Other Comments
The previous `!event confirm` allowed the cancellation of the event - it is possible that this is the "new normal", but it is not as intuitive to have to confirm and then cancel.
This was replicated on a couple of different servers. The later (where the screenshots were generated) was a bare metal installation with a new calendar and no events.

**Comment by NovaFox161** [comment]
This has been fixed in 8672edf6fffd9bd08dc696917a3613a705694326 and will be deployed in the 4.1.4 update (likely coming out in the upcoming week)

Thank you for the bug report!
