### ISSUE TITLE
Add all-day & multi-day support to /displaycal

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#122]
**Is your improvement request related to a problem? Please describe.**
Currently `/displaycal` doesn't curently handle multi-day events well, only showing the first day. It also displays all-day events as running from "12:00am - 12:00am" (or "00:00 - 00:00" in 24-hour mode).

**Describe the solution you'd like**
The overview should display an event on each day it's happening.
It should also display all-day events as "All Day"

**Describe alternatives you've considered**
Creating a separate event for each day of a multi-day event.

**Additional context**
![image](https://user-images.githubusercontent.com/19196582/145092656-946e249d-fb13-4b7e-9027-5e5fd8d2cec7.png)

**Comment by NovaFox161** [comment]
Currently the way the code is, it grabs the next 15 events, then breaks them into groups of what day they start in, then builds the embed. This makes it easy to build the embed with events split up by day, but means that showing events on multiple days is impossible.

Tbh, I'm not really sure how I would (logically) get to doing this without some complicated code... But I see the issue with the current system.

**Comment by smnc** [comment]
In the short run, how about the other half, listing all-day events as "All-Day" instead of "00:00 - 00:00"

**Comment by NovaFox161** [comment]
I think I can do something like that. 

Not sure how I would show it for multiple days tho unfortunately. Or rather, I *could* do it, but I'm not sure of a way to do it where my code would be readable and maintainable

**Comment by smnc** [comment]
Noted. I'll handle things the manual way for now while we mull this over.
