### ISSUE TITLE
Add days of the week to /displaycal

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#124]
**Is your improvement request related to a problem? Please describe.**
Currently the `/displaycal` overview only displays event dates, but does not display days of the week. This makes it harder to determine when events are.

**Describe the solution you'd like**
Have the day of the week displayed as part of the date.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by NovaFox161** [comment]
Oh, you want it to display days without events? is that it or am I missing something?

**Comment by smnc** [comment]
Currently is shows this:
![image](https://user-images.githubusercontent.com/19196582/145260963-b6c70c14-7b99-48c1-a5d9-7e15f0b821af.png)
The date without the day of the week.

I'm thinking just add the day of the week
`Friday - 17 December 2021`
Or something similar.

**Comment by NovaFox161** [comment]
oh. Yeah, that's hella easy to add.

**Comment by smnc** [comment]
I figured.
Easy ease-of-use improvement.
How about #122?

**Comment by NovaFox161** [comment]
Added in 63a35d5
Will be available in the next update
