### ISSUE TITLE
Display event location in /DisplayCal

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#125]
**Is your feature request related to a problem? Please describe.**
Some guilds have events occuring in many locations and would find it helpful to have an option to diplay event locations in `/DisplayCal`

**Describe the solution you'd like**
An option to enable `/DisplayCal` to display locations with each event.

**Describe alternatives you've considered**
Using the web calendar.

**Comment by NovaFox161** [comment]
Added in latest commit, will be available in next update
