### ISSUE TITLE
Can't clear "Location" property

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#136]
## *Who* is the bug affecting?
All users

## *What* is affected by this bug?
The bot

## *When* does this occur?
When editing an event

## *Where* on the platform does it happen?
event creation/editing wizard

## *How* do we replicate the issue?
Internal calendars have no way to clear a location once the property has a value

## Expected behavior (i.e. solution)
Should be able to set it to an empty value

**Comment by NovaFox161** [comment]
This will be resolved in 4.2.2

Event names/descriptions/locations can now be removed in 3 ways:
- not providing the now optional argument in the name/desc/location commands
- Setting it to "N/a"
- Setting it to "None"
