### ISSUE TITLE
How to load google calendar on Discal

### ISSUE THREAD

**Issue by cloner99** [DreamExposure/DisCal-Discord-Bot#164]
Hi!

I wish to know how to pend my google calendar to the Discal on discord server.

**Comment by NovaFox161** [comment]
Importing/using an already existing calendar directly is not currently supported as support for it broke awhile back and I haven't yet fixed it.


For now, you can refer to the commands documentation for how to create a calendar and events. https://github.com/DreamExposure/DisCal-Discord-Bot/?tab=readme-ov-file#%EF%B8%8F-commands
