### ISSUE TITLE
Issue with Date/Time

### ISSUE THREAD

**Issue by DarbiiRue** [DreamExposure/DisCal-Discord-Bot#28]
Hi there,

I chose Americas/New York as my timezone, but when I create an event, it always puts it a day ahead, and the hours are incorrect, like it's pulling from a different timezone. Can anyone help me sort this out? Is it a bug? Thanks!

**Comment by MichaelCalleia** [comment]
Similar issue. 8pm ET is announced as 4pm ET. If I check the event, the time is correct.

**Comment by NovaFox161** [comment]
This is fixed in the rewrite which is just a few steps away from being deployed to production.
