### ISSUE TITLE
Specific Event Notifications not Going Off

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#51]
## *Who* is the bug affecting?
Anyone who needs to be notified

## *What* is affected by this bug?
The Bot

## *When* does this occur?
When an announcement is supposed to go off and doesn't

## *Where* on the platform does it happen?
In whatever channel the announcement is supposed to happen in.

## *How* do we replicate the issue?
Create a specific annoucement (mine are on an External Calendar - not sure if that matters)

## Expected behavior (i.e. solution)
Announcement should go off and notify the users.

## Other Comments
Thanks for all the hard work.

**Comment by NovaFox161** [comment]
I believe I have this fixed in the latest commit. I'll be getting it tested later today/tomorrow

**Comment by smnc** [comment]
I'll hold off on reformating my events to use colours for now then. Thanks for getting to it so quickly!

**Comment by NovaFox161** [comment]
Fixed in latest release
