### ISSUE TITLE
Ability to limit RSVPs

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#53]
**Is your feature request related to a problem? Please describe.**
Sometimes events have a limited number of spots. The ability to limit RSVPs would make this much easier to manage through the bot.

**Describe the solution you'd like**
The ability to set the maximum number of RSVPs for a particular event, or set a default maximum for new events.

**Describe alternatives you've considered**
Alternatively a command to close/disable RSVPs would work as well, although it has issues.

 **Additional context**
RPG Schedule Bot has this feature, with a waitlist:
![image](https://user-images.githubusercontent.com/19196582/91609896-3d152580-e946-11ea-8fc9-e926a418ccc7.png)

**Comment by NovaFox161** [comment]
Added in commit a853cbeee84a3972da4d8660193ae385b6875305

Still needs testing, will close issue once I have tested this.

**Comment by NovaFox161** [comment]
Finalized in commit 437a7b99e13dcf3a06c42a5072b606978af7b341

Working properly, good to go for 4.1.0 release. Eventually this will tie into reactions and some other related features, for now is just a simple command.

`!rsvp limit <event-id> <#limit>`to change the limit, with -1 being unlimited.
