### ISSUE TITLE
Link Directly to Google Calendar When Clicking "Guild Calendar" from Discord

### ISSUE THREAD

**Issue by miri1983** [DreamExposure/DisCal-Discord-Bot#55]
**Is your feature request related to a problem? Please describe.**
Not exactly a problem, more an inconvenience. When clicking on "Guild Calendar" from Discord, it is inconvenient to have to go to the DisCal website, then click on "View in Google Calendar".

**Describe the solution you'd like**
It would be great if there is a setup option so that when clicking on "Guild Calendar" from Discord it would go directly to Google Calendar instead of to the DisCal website first.

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by NovaFox161** [comment]
This used to be the default, but we've been focusing on getting the discal site more integrated with the bot directly.

**Comment by NovaFox161** [comment]
Closing. With the new web calendar view, this is unneeded as it functions well, and the button to viewing on google is just one extra click. 

Overall, we would like to integrate more inline with our own website as we are planning on expanding into supporting more calendar services and having the option to link to google directly would defeat that purpose and make further changes harder when adding in other service support.
