### ISSUE TITLE
Unable to delete event

### ISSUE THREAD

**Issue by tulayha** [DreamExposure/DisCal-Discord-Bot#56]
Executing `!event delete <event_id>` returns `Event successfully deleted` but the event still exists on checking with `!events`

- it is a recurring event and i tried both with the initial part of event id and complete event id, with same results

- checked the dates to make sure the first upcoming event wasnt deleted instead of the next one showing, so its not that either

- only checked with `recur` type events, havent checked other types

**Comment by NovaFox161** [comment]
I'll have to enable logging for event deletion because I'm not currently seeing any errors, but its possible in the rewrite I broke something by leaving out a value much like how event edit confirmation was broken due to the event ID being left out of the request.

**Comment by tulayha** [comment]
ill use the command again a couple times again so it shows in logs

**Comment by tulayha** [comment]
> I'll have to enable logging for event deletion because I'm not currently seeing any errors, but its possible in the rewrite I broke something by leaving out a value much like how event edit confirmation was broken due to the event ID being left out of the request.

tried it a couple times, should show in logs

**Comment by NovaFox161** [comment]
Should be fixed in commit 786b00e2b5915e2960769dc9508971dde37cbcf4

Further errors in event deletions will be logged automatically now
