### ISSUE TITLE
Bot responds to original prefix even after setting a new one

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#60]
## *Who* is the bug affecting?
Everyone inputting commands

## *What* is affected by this bug?
The bot

## *When* does this occur?
Whenever inputting a command in Discord

## *Where* on the platform does it happen?
Discord command interface

## *How* do we replicate the issue?
Change the prefix of the bot to anything other than the default, but the bot will still respond to the default `!` prefix as well as the new prefix.

## Expected behavior (i.e. solution)
Bot should only respond to new prefix (and @'ing the bot)

**Comment by NovaFox161** [comment]
This should be fixed in commit dbd6771d557def6ef9e8cb4d51871ffd2b42fe5c and has been deployed as a snapshot/hot-fix version as this was too urgent to wait for the 4.1.0 milestone.

Issue was related to not saving new guild settings due to empty Mono flow making the null/present check redundant.
