### ISSUE TITLE
Timezone Shenanigans in DisCal web calendar page

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#61]
## *Who* is the bug affecting?
Regular users checking the DisCal calendar webpage

## *What* is affected by this bug?
The website

## *When* does this occur?
Not sure.

## *Where* on the platform does it happen?
Calendar page on the website

## *How* do we replicate the issue?
Not sure

## Expected behavior (i.e. solution)
Web Calendar should show events correctly

**Comment by NovaFox161** [comment]
Can't really seem to figure out a fix for this, gonna look into a full fledged calendar library/styles for web and maybe use that.

Also, the specific shenanigans is that for whatever reason it showing in local time rather than calendar time.
