### ISSUE TITLE
Help descriptions do not reflect changed command prefix

### ISSUE THREAD

**Issue by Tdue21** [DreamExposure/DisCal-Discord-Bot#62]
**Is your improvement request related to a problem? Please describe.**
I have changed the prefix in order to avoid conflict with another bot. But help descriptions always display the default prefix in examples. 

**Describe the solution you'd like**
Any help description with examples should use the configured prefix instead of the default.

**Comment by NovaFox161** [comment]
This is/will be negated once fully converted to slash commands
 #111
