### ISSUE TITLE
Prefix Change Reverting

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#65]
## *Who* is the bug affecting?
Anyone giving commands to the bot in a specific 738513735605420042

## *What* is affected by this bug?
The bot

## *When* does this occur?
Appears to be random at this point

## *Where* on the platform does it happen?
Commands issued in Discord

## *How* do we replicate the issue?
Unknown

## Expected behavior (i.e. solution)
Prefix changes should stick

## Other Comments
`#dc-ticket-1743`

**Comment by NovaFox161** [comment]
Reference my comment on #66 about theories of where this is occurring. Will need to know what users are doing with the bot between the time the prefix has been set and when it appears to have reverted. Maybe they are interacting with the dashboard/website and its causing issues? I really have no clue and need further details as I just cannot replicate.

**Comment by NovaFox161** [comment]
This should be fixed in commit dbd6771d557def6ef9e8cb4d51871ffd2b42fe5c and has been deployed as a snapshot/hot-fix version as this was too urgent to wait for the 4.1.0 milestone.

Issue was related to not saving new guild settings due to empty Mono flow making the null/present check redundant.
