### ISSUE TITLE
24 Hour/Military Time

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#68]
**Is your feature request related to a problem? Please describe.**
Most countries outside of CANZUK, the USA, and other former British colonies user 24 hour time. 

**Describe the solution you'd like**
The bot should have an option to switch to 24 hour time

**Describe alternatives you've considered**
None

**Additional context**
I also user 24 time even though I'm in Canada ;)

**Comment by NovaFox161** [comment]
This has been implemented in the database for quite some time now, its just a matter of getting all of the displays the user can see to respect the setting (event embeds, time embeds, announcement embeds) and adding a toggle command for it.

Having this on the website tho is another task entirely as I don't know if its something I can control or if its built in localization with browsers.

**Comment by smnc** [comment]
I know for Google Calendar it's a setting in the website
![image](https://user-images.githubusercontent.com/19196582/92988698-df332280-f49b-11ea-98a3-656382a820dc.png)

**Comment by NovaFox161** [comment]
Added support in commit 9f45b5d

Tested and working, can be toggled with `!discal timeFormat`

Currently on schedule to be deployed in the 4.1.0 release
