### ISSUE TITLE
More Announcement Shenanigans

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#69]
## *Who* is the bug affecting?
Users in server 519475451006025738

## *What* is affected by this bug?
The bot

## *When* does this occur?
When attempting to edit an announcement

## *Where* on the platform does it happen?
Announcement Creation Wizard

## *How* do we replicate the issue?
Trying to create or edit an event in 519475451006025738

## Expected behavior (i.e. solution)
Announcement Wizard should work

## Other Comments
Super funky. User reported announcements not going off but everything seemed to be set correctly. He invited me to the server to check. Announcements appeared correct but when trying to edit one the bot didn't repond, but did generate an error in the log:
[Error 519475451006025738.txt](https://github.com/DreamExposure/DisCal-Discord-Bot/files/5213491/Error.519475451006025738.txt)

Attempted to create new nnouncement. Seemed to be fine, but crashed out partway through. No error in the log, but the Announcement Creation Wizard just died after setting type and event ID but before setting channel or time.

Ticket #1757

**Comment by NovaFox161** [comment]
I haven't seen any recent reports of this (its been over a year), and with the new code I've been deploying this should be as good as resolved.
