### ISSUE TITLE
Recurrence every 3rd Tuesday of the month for example

### ISSUE THREAD

**Issue by AmberElferink** [DreamExposure/DisCal-Discord-Bot#70]
The club I am using this for, has a meeting every first Tuesday of the month. I know there is a monthly recurrence option, but as far as I'm aware, this will just take the numerical date and repeat it each month.

I would like to be able to set the recurrence to "Day" "Week nr in month"  monthly. Is this possible?

For now my only option I can see is to find another bot, or to make the events manually.

Thanks for considering!

**Comment by smnc** [comment]
Google Calendar can do this natively. I'm thinking this should be combined with #81?

**Comment by NovaFox161** [comment]
Yeah, going to close this as a duplicate of #81 and move the conversation for this there.
