### ISSUE TITLE
Calender Creation Confirm 

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#72]
## *Who* is the bug affecting?
Admins setting up the bot

## *What* is affected by this bug?
The bot

## *When* does this occur?
When creating a calendar

## *Where* on the platform does it happen?
Calendar Creation Wizard

## *How* do we replicate the issue?
Sporadic. Happens sometimes, other times not.
Calender fails to respond to `!cal confirm`

## Expected behavior (i.e. solution)
Calender should be created

## Other Comments
Possibly related to #67 
Tickets #1811, #1814, #1824, #1826, #1827 all seem to be examples.

**Comment by smnc** [comment]
Add #1830 to the list.

**Comment by smnc** [comment]
Add #1832 to the list.

**Comment by smnc** [comment]
Add #1835 too.

Looks like the problem might be shard 8. Still waiting for confirmation from ticke #1827, but the rest of the servers all appear to be shard 8.

**Comment by NovaFox161** [comment]
Ever since pushing out a snapshot update that fixed issues with guild data saving, I haven't been able to replicate this issue nor have we gotten any recent reports since then of calendar creation failing. 

I know neither of those issues are linked, but there were other minimal changes in those commits that are deployed that could have solved the issue...

**Comment by vanyamil** [comment]
Just got this bug. Shard 8 currently displaying about a Gb of RAM use above almost all other shards. Server ID 792426587445657610, is it on there?

**Comment by NovaFox161** [comment]
> 
> 
> Just got this bug. Shard 8 currently displaying about a Gb of RAM use above almost all other shards. Server ID 792426587445657610, is it on there?

No, that's on shard 6. Increased RAM usage doesn't always indicate an issue, could just mean increased usage on that one shard compared to others.

**Comment by vanyamil** [comment]
Got fixed now - the previous commands from an hour prior ran, supposedly creating the calendar twice. However, !cal review showed no calendar was recorded. Creating it again worked out well, with nearly no delay (no more than expected from API communication).

**Comment by NovaFox161** [comment]
Considering this now resolved since all related code has since been rewritten and we have had no further reports in nearly a year.
