### ISSUE TITLE
Make RSVP user friendly

### ISSUE THREAD

**Issue by GreenieT87** [DreamExposure/DisCal-Discord-Bot#73]
**Is your feature request related to a problem? Please describe.**
RSVP is unusable needing the "announcement id", specially for people using phones

**Describe the solution you'd like**
anything else than needing a UUID, Event name for example 

**Describe alternatives you've considered**
#52 

**Additional context**
How are people using this feature in this state? Iam a techie but hell. It is not possible to copy the ID on a phone out of the embbeded mesage... are you expecting peopel to type that manually.

**Comment by NovaFox161** [comment]
Duplicate of #52 please add as comment to that issue instead.
