### ISSUE TITLE
Event Edititng Bug

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#74]
## *Who* is the bug affecting?
Users attempting to edit events

## *What* is affected by this bug?
The bot

## *When* does this occur?
When editing an existing event in th bot

## *Where* on the platform does it happen?
Event Creation/Editing Wizard

## *How* do we replicate the issue?
Attempting to edit events sometimes causes the bot to refuse to confirm the event. Appears to be sporradic.

## Expected behavior (i.e. solution)
Event should be confirmed.

## Other Comments
Ticket #1833

**Comment by NovaFox161** [comment]
I believe I have fixed this issue in a semi-recent commit that was deployed in a snapshot/hotfix. Please reopen if I am mistaken
