### ISSUE TITLE
Assign a role on Event RSVP

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#78]
**Is your feature request related to a problem? Please describe.**
No, but would tie into issue #52 nicely.

**Describe the solution you'd like**
The ability for the bot to assign a role to users who RSVP to an event.

**Describe alternatives you've considered**
The functionality could be gained once #52 is complete by using a combination of DisCal and a dedicated reaction role bot like Zira.

**Additional context**
There are many good uses cases for an RSVP also assigning a role. Access to special events, or even recurring events could be easily regulated. Announceent subsciption pings could be sent to the role assigned by the bot too.

**Comment by NovaFox161** [comment]
Just realized, how would we handle removing RSVP roles?
More info would be greatly appreciated.

**Comment by smnc** [comment]
I wouldn't (remove the roles). 
The main use I see is for time-limited events with temporary roles. After the event the organizer just deletes the role (and probably the channels) from the server (that's what I do).

Alternatively, (and this is by far the bigger PITA), the bot could check the event end kill the role a selected amount of time after the event ends, but this seems like it's not worth the effort and would almost certainly have issues.

**Comment by NovaFox161** [comment]
Okay, so the flow would be:
Create event, choose role that users will get when RSVPing, assign role on user, and at that point its no longer something for the bot to handle unless they remove their RSVP in-which the bot will remove the role automatically, otherwise it is up to the server admins to handle it?

**Comment by smnc** [comment]
That's my thought yes.

**Comment by NovaFox161** [comment]
Should this be part of the event creation system, or should this be tied more directly to the RSVP (!event rsvpRole <roleName>) or (!rsvp role <event-id> <role>)?

I think it would make sense to put this on rsvp data, but that would mean recurring events don't respect the same role, tho, that's the case for how I implemented rsvp limits unless we change that to be tied to events directly, which would make recurring events respect the same limit and role... But it would make event creation more complicated as those are then 2 additional commands that may be needed. 

I think if we go the second way (tying to events directly) that would mean in the future overhauling the calendar/event/announcement creation wizards to be more user friendly. However, I honestly do way more with backend so I have literally no idea how I would make it more user friendly without some UI/UX people here or a lot of community feedback on their thoughts.

**Comment by smnc** [comment]
Yeah, I think it makes more sense to tie it to RSVPs
It's a bit of a pain if you want to use it for recurring events, but I think that's an edge case.
And yeah, we're gonna have to find someone to rething the UI/UX at some point...

**Comment by NovaFox161** [comment]
One last question while I am working on implementing this feature. Should this be a patron only feature, or should this be a base feature?

**Comment by smnc** [comment]
Thew way I see it is new features like this should start out as Patreon and trickle down over time as other new features are added.
It is "Early Access" for a reason. You donate, you get first dibs.

**Comment by NovaFox161** [comment]
Another question!!! I had this while working on adding this all in.

Should the role be retroactively applied? As in, if say 5 people RSVP to the event, and then the server admins add a role for users to get when RSVPing, should it add the role to the users who are already RSVP'd? 

Code structure won't change much to add this in, just trying to figure out if I should add this functionality.

**Comment by smnc** [comment]
Yeah, that'd be a huge benefit!

**Comment by NovaFox161** [comment]
Added in commit: 302b71f

Will need a few rounds of testing, but other than the one TODO for adding a check if the bot can assign the role to the user (which I have to wait for D4J to accept my PR), it should be completely done.

**Comment by NovaFox161** [comment]
Once I get the issue with netty resolved, this can be merged from the feature branch to master for 4.1.0
