### ISSUE TITLE
!events ongoing

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#79]
**Is your feature request related to a problem? Please describe.**
Currently there is no way for the bot to display events that are ongoing, only events that are upcoming

**Describe the solution you'd like**
The ability to display events that a currently ongoing instead of ones that are upcoming 

**Describe alternatives you've considered**
Viewing on Google Calendar

**Additional context**
> There's no direct way in the API do find "ongoing/current" events. The only way I could do that, is to find events in a range, from starting at x time in the past all the way to events that start at the current moment in time.

> Then from that, go through those events and find only the ones in which the end time is after the current time, and then display those to the user. That would show only events that are currently happening now.

> However, this creates a problem, what is that initial x value cut off? 1 day ago? 2? a week? a month? Its a tradeoff between making sure we get as many of the potential current events and getting supplied a huge event list that takes a lot of time to process and verify if its "ongoing"

> I suppose I could do the solution above and just set the range to 2 weeks or something maybe?

**Comment by NovaFox161** [comment]
Added in commit 5aad103

Currently only accessible to dev and patron guilds for testing/early access. Will be deployed to some shards for testing later this week, right now only on test bot

**Comment by NovaFox161** [comment]
API still needs to be written

**Comment by NovaFox161** [comment]
Completed and working
