### ISSUE TITLE
Bot won't post to News/Announcement Channels

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#83]
## *Who* is the bug affecting?
Users creating announcements

## *What* is affected by this bug?
The bot

## *When* does this occur?
When creating or editing an announcement and setting the channel

## *Where* on the platform does it happen?
Announcement creation wizard

## *How* do we replicate the issue?
Create an announcement and try to set it to post in a news/announcement channel

## Expected behavior (i.e. solution)
Bot should be able to post in news/announcement channel

## Other Comments
Ticket 1977

**Comment by NovaFox161** [comment]
Basically go through the bot and change references from `TextChannel` to `GuildMessageChannel` and it should "just work"

**Comment by NovaFox161** [comment]
Commit ff1691e should fix this issue, but will need testing to confirm both that commands work in the channel, as well as can post announcements.

This commit does not however add support to "publish" to news channels, just post messages in news channels.

**Comment by NovaFox161** [comment]
Confirmed working.
