### ISSUE TITLE
Remove old URL's from docs

### ISSUE THREAD

**Issue by thunderstorm010** [DreamExposure/DisCal-Discord-Bot#88]
**Is your improvement request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Removing the old URL's and add the new DreamExposure URL's from/to code.

**Additional context**
https://github.com/DreamExposure/DisCal-Discord-Bot/blob/f803a6d9c468e24658ac6bb4e0ec7082e040db06/core/src/main/java/org/dreamexposure/discal/core/crypto/KeyGenerator.java#L8

**Comment by thunderstorm010** [comment]
Edit: A Kotlin rewrite is going on and this shouldn't be needed.

**Comment by NovaFox161** [comment]
Its not a full rewrite, mostly just the data objects being converted to proper kotlin data classes and stuff. Majority of discal code is not changing
