### ISSUE TITLE
Calendar Display in Discord

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#90]
**Is your feature request related to a problem? Please describe.**
Having to leave discord for the web is a sub-optimal way to view the calendar "at-a-glance", and the !events _x_ command is less than ideal too.

**Describe the solution you'd like**
The ability for Discord to display a clean embed with the next week of calendar events.

**Describe alternatives you've considered**
Using Niles Bot, lol

**Additional context**
User shared this screenshot of a possible solution: 
![image](https://user-images.githubusercontent.com/19196582/108148134-328a4c00-709e-11eb-9682-b3d78c7a791e.png)
Niles bot already has this functionality too:
![image](https://user-images.githubusercontent.com/19196582/108148185-49c93980-709e-11eb-8004-05594e80c796.png)
Niles Bot is able to refresh/update a displayed calendar too, both on command and also automatically.

**Comment by NovaFox161** [comment]
This has been added and will be available in the 4.1.4 release. 

There's still some oddities for me to figure out, but for all intents and purposes the feature is complete for users to use come release day.
