### ISSUE TITLE
Multi-line Event Descriptions

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#92]
**Is your feature request related to a problem? Please describe.**
Users should be able to create multi-line event descriptions.

**Describe the solution you'd like**
The ability to create multi-line event descriptions

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/19196582/109334396-a8c14800-782e-11eb-9286-225499608293.png)

**Comment by rio197** [comment]
+1

**Comment by NovaFox161** [comment]
New line characters are now properly escaped and rendered as a new line, including the ical standard newline.


HOWEVER:
using `shift+enter` to make a new line does not currently work (except on android) in slash commands. This is something discord is going to support ("multi-line slash command options"). Until then, entering `\n` or any variation of that will work.
