### ISSUE TITLE
Change the embed colour of "Color" type announcements to match

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#93]
**Is your feature request related to a problem? Please describe.**
There is no way at a glance to tell what colour a "color" type announcement is set too

**Describe the solution you'd like**
Have the embed colour match the set "color" of an announcement

**Describe alternatives you've considered**
None

**Additional context**
Event embeds match their "colors" seems silly that announcements don't

**Comment by NovaFox161** [comment]
Do announcements really not? I know when they announce they match the color, but in the editor/preview do they not match???

**Comment by smnc** [comment]
Apparently this was an issue of my colourblindness not seeing colours properly. When testing again with colours I can see more readily, it seems to work just fine.

**Comment by NovaFox161** [comment]
Good job <3
