### ISSUE TITLE
"Colour" alias for "Color" not documented

### ISSUE THREAD

**Issue by smnc** [DreamExposure/DisCal-Discord-Bot#94]
**Is your feature request related to a problem? Please describe.**
The bot doccumentation does not list "colour" as an alias for "color" even though the bot supports it.

**Describe the solution you'd like**
The bot doccumentation fo be updated.

**Describe alternatives you've considered**
All Americans could learn to spell the word correctly 😜 

**Additional context**
If you could also get Americans to spell armour correctly and pronounced the letter "z" as zed too, I'd really appreciate it.

**Comment by NovaFox161** [comment]
This is actually already supported for both commands lol

Its just not on the commands page on the bot's site.

I guess this issue is notification for clarifying the documentation on the site so that its more clear that `colour` is actually valid

**Comment by smnc** [comment]
Sunofagun. Probably should have tested before complaining.
Do you have a fix for "z" and armour too? LOL

**Comment by NovaFox161** [comment]
I think that is out of scope for a calendar bot lol

**Comment by NovaFox161** [comment]
Fixed in commit 3483016
